instance:
  _target_: models.dinov2_with_bert.DinoV2WithBertLoRA
  frozen: True
  q_former: True
  # pretrained_model_checkpoint: ${hydra:runtime.cwd}/checkpoints/Resnet50_trainBackbonedinov2_with_bert_2025-05-17_14-58-48_dinov2_distillbert_lora_only_best.pt
  frozen_backbone: True

name: dinov2_bert
train_bert_tiny: True
model_path: bert-base-uncased
tokenizer_path: bert-base-uncased
# load_model_path: Syldehayem/train_bert-base-uncased_100
epochs: 20