instance: 
  _target_: models.dinov2_with_bert.DinoV2WithBert
  frozen: True
name: dinov2_with_bert
train_bert_tiny: False
model_path: distilbert-base-uncased
tokenizer_path: distilbert-base-uncased
load_model_path: train_distilbert-base-uncased_20
epochs: 5