instance: 
  _target_: models.dinov2_with_bert.DinoV2WithBert
  frozen: True
name: dinov2_with_bert
train_bert_tiny: True
model_path: distilbert-base-uncased
tokenizer_path: distilbert-base-uncased
# load_model_path: Syldehayem/train_distilbert-base-uncased_30
epochs: 100