instance: 
  _target_: models.dinov2_with_bert.DinoV2WithBert
  frozen: True
name: dinov2_with_bert
train_bert_tiny: True
model_path: elihoole/roberta-base
tokenizer_path: elihoole/roberta-base
# load_model_path: Syldehayem/train_distilbert-base-uncased_100
epochs: 10